[project]
name = "mini-coding-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jingjun", email = "254032134@qq.com" }
]
requires-python = ">=3.11"
dependencies = [
    "openai>=3.14.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]

[project.scripts]
mini-coding-agent = "mini_coding_agent.main:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
